#### Dictionary

In [21]:
d = {'A':1,'B':2,'C':3,'D':4,'E':5}
for i in d:
    print(i,end="")

ABCDE

In [22]:
for i in d.values():
    print(i,end="")

12345

In [23]:
for i in d.keys():
    print(i,end="")

ABCDE

In [25]:
for i in d.items():
    print(i,end="")

('A', 1)('B', 2)('C', 3)('D', 4)('E', 5)

#### Dict comprehensions

In [26]:
d1 = {i:i*i for i in range(5)}
d1

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [28]:
L = range(7)
day = ['sun','mon','tue','wed','thur','fri','sat']
days_num = {k:v for (k,v) in zip(L,day)}
days_num

{0: 'sun', 1: 'mon', 2: 'tue', 3: 'wed', 4: 'thur', 5: 'fri', 6: 'sat'}

In [31]:
d1.update(days_num)
print(d1)

{0: 'sun', 1: 'mon', 2: 'tue', 3: 'wed', 4: 'thur', 5: 'fri', 6: 'sat'}


In [33]:
d = {"id":102,"name":"ravi","age":24}
d.setdefault("place","hyd")
print(d)

{'id': 102, 'name': 'ravi', 'age': 24, 'place': 'hyd'}


In [34]:
d1 = dict.fromkeys(L)
print(d1)

{0: None, 1: None, 2: None, 3: None, 4: None, 5: None, 6: None}


In [35]:
d1 = dict.fromkeys(L,10)
print(d1)

{0: 10, 1: 10, 2: 10, 3: 10, 4: 10, 5: 10, 6: 10}


In [36]:
d = {"id":102,"name":"ravi","age":24}
k = d.keys()
print(k)

dict_keys(['id', 'name', 'age'])


In [37]:
new_dict = dict.fromkeys(k,100)
print(new_dict)

{'id': 100, 'name': 100, 'age': 100}


In [38]:
l = list(new_dict)
l

['id', 'name', 'age']

In [40]:
l = list(new_dict.values())
l

[100, 100, 100]

In [41]:
l = list(new_dict.items())
l

[('id', 100), ('name', 100), ('age', 100)]

### Functions

#### Fibonacci using functions

In [44]:
l = []
def fib(n):
    n1 = 0
    n2 = 1
    i = 1
    while i<=n:
        #print(n1)
        l.append(n1)
        c = n1+n2
        n1 = n2
        n2 = c
        i += 1
    return l

In [45]:
fib(5)

[0, 1, 1, 2, 3]

#### Lambda function

In [46]:
x = lambda x: x*x #lambda param1:param1*param1

In [47]:
x(10)

100

In [48]:
import math
d = lambda p1,p2: math.sqrt(p1**2+p2**2)

In [49]:
d(10,20)

22.360679774997898

In [50]:
def area(d1,d2):
    rec = d1*d2
    tri = d1*d2/2
    return (rec,tri)

In [51]:
r, t = area(10,20)
print(r,t)

200 100.0


In [52]:
def convert(n,base):
    L = []
    while(n>0):
        bit = n%base
        L.insert(0,bit)
        n = n//base
    return L

In [53]:
convert(10,2)

[1, 0, 1, 0]

In [54]:
def convert(n,base=2):
    L = []
    while(n>0):
        bit = n%base
        L.insert(0,bit)
        n = n//base
    return L

In [55]:
convert(15)

[1, 1, 1, 1]

In [57]:
convert(200,8)

[3, 1, 0]

In [58]:
def pass_val(s):
    s1 = "hai"
    s = s+s1
    print("inside function",s)

In [59]:
x = "hello"
pass_val(x)
print("outside function",x)

inside function hellohai
outside function hello


In [60]:
def pass_ref(L):
    L.append(100)
    print("iside function L=",L)

In [61]:
x=[1,5,10]
pass_ref(x)
print("ouside function:",x)

iside function L= [1, 5, 10, 100]
ouside function: [1, 5, 10, 100]


#### Recursive Function

In [155]:
# Factorial
def factorial(n):
    if n>0:
        if n==1:
            return 1
        else:
            return n*factorial(n-1)
    else:
        print(n,"is not valid")
        return 

In [156]:
factorial(-5)

-5 is not valid


In [157]:
#print even numbers between n1 and n2
def even_num(n1,n2):
    if n1>n2:
        return
    else:
        if n1%2==0:
            print(n1,end="")
        even_num(n1+1,n2)

In [158]:
even_num(5,10)

6810

In [160]:
#display values between n1 and n2 using recurssion
def display(n1,n2):
    if n1>n2:
        return
    else:
        print(n1,end="")
    display(n1+1,n2)
display(2,8)

2345678

In [164]:
#sum of digits
def sum_digit(n):
    if n==0:
        return 0
    else:
        return n%10 +sum_digit(n//10)

In [165]:
sum_digit(123456)

21

In [ ]:
#list of digits of n ex:n=1654 out:[4,5,6,1]

In [185]:
l = []
def list_digit(n):
    if n==0:
        return l 
    else:
        l.append(n%10)
        return list_digit(n//10)
        

In [186]:
x = list_digit(1654)

In [190]:
print("original",x)
x.reverse()
print("reverse of x = ",x)

original [4, 5, 6, 1]
reverse of x =  [1, 6, 5, 4]


In [196]:
def func():
    x=100
    print("inside function",x)

In [197]:
x = 10
func()
print("ouside function",x)

inside function 100
ouside function 10


In [198]:
def func():
    global x
    x += 10
    print("inside function",x)

In [199]:
func()

inside function 20


#### Random Numbers

In [200]:
import random
# random intergers
r1 = random.randrange(10)
print(r1)

9


In [208]:
r1 = random.randrange(1,10,3)
print(r1)

7


In [209]:
#from list
x = [12,"hello",3.4,True]
a = random.choices(x,k=3)
print(a)

[12, True, 12]


In [217]:
#from tuple
x = (12,"hello",3.4,True)
a = random.choices(x,k=3)
print(a)

[True, 12, 'hello']


In [212]:
#from dictionary
x = {1:12,2:"hello",3:3.4,4:True}
a = random.choices(list(x))
print(a)

[1]


In [215]:
x = (12,"hello",3.4,True)
random.seed(42)
a = random.choices(x,k=3)
print(a)

[3.4, 12, 'hello']


In [220]:
random.seed(2)
a = random.choices(range(50,100),k=3)
print(a)

[97, 97, 52]


#### Input/Output

In [221]:
n = int(input())
print(type(n))

23
<class 'int'>


In [229]:
n = input("enter element")
print(eval(n))

enter element10 * 4/2
20.0


#### unformatted output

In [232]:
x,y = 10,30
print(x,y)
print(x,y,sep=";")
print(x,y,sep=",")
print(x,y,sep=";",end="#")

10 30
10;30
10,30
10;30#

#### formatted output
#### 1 String.format

In [234]:
print("x value {},y value {}".format(x,y))

x value 10,y value 30


In [235]:
print("y value {1},x value {0}".format(x,y))

y value 30,x value 10


In [236]:
print("y value {a},x value {b}".format(b=x,a=y))

y value 30,x value 10


#### 2. String % values

In [239]:
x, y = 23.45,345.6789  # %F %f %e %E %g %G (float)
print("x=%f y=%f" % (x,y))

x=23.450000 y=345.678900


In [245]:
x,y = 0.0045, 45.678
print("x=%e y=%f" % (x,y))

x=4.500000e-03 y=45.678000


In [246]:
print("x=%E y=%f" % (x,y))

x=4.500000E-03 y=45.678000


In [247]:
x,y = 45.32, 0.5564
print("x=%F y=%F" % (x,y))

x=45.320000 y=0.556400


In [248]:
print("x=%g y=%g" % (x,y))

x=45.32 y=0.5564


In [249]:
# %d for decimal
x,y = -200,34
print("x=%d y=%d" % (x,y))

x=-200 y=34


In [250]:
# %c Char and %s for String
x,y = "hello",'E'
print("x=%s y=%c" % (x,y))

x=hello y=E


In [251]:
# %o Octal %x Hex decimal
print("%o" % (16))

20


In [252]:
print("%x" %(252))

fc


In [253]:
print("%X" %(252))

FC


In [254]:
x = float('inf')
print("x = %f" %(x))

x = inf


In [255]:
x = float('inf')
print("x = %F" %(x))

x = INF


In [257]:
x = float('nan')
print("x = %F" %(x))

x = NAN


In [260]:
x = "hello"
print("%s" %(x))
print("%20s" %(x))

hello
               hello


In [264]:
x,y = 12.34,34
print("%5f %7d" %(x,y))

12.340000      34


In [267]:
x,y = 12.345567,"hello hai"
print("%.2f %.8s" %(x,y))

12.35 hello ha


In [274]:
x,y = 12.34,34.900087
print("x=%5f" %(x))
print("y=%+7d" %(y))
print("x=%-5f y=%7d" %(x,y))

x=12.340000
y=    +34
x=12.340000 y=     34


In [278]:
#flag = 0
x=89
print("x=%010d" %(x))

x=0000000089


#### Numpy

In [290]:
import numpy as np
n = np.array([(1,2,3),(2,3,4)])
print(n)

[[1 2 3]
 [2 3 4]]


In [291]:
np.array(np.mat('1 2; 3 4'))

array([[1, 2],
       [3, 4]])

In [292]:
x = np.full((3,4),10)
print(x)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [297]:
x = np.full((3,4),"hai")
print(x)

[['hai' 'hai' 'hai' 'hai']
 ['hai' 'hai' 'hai' 'hai']
 ['hai' 'hai' 'hai' 'hai']]


In [298]:
np.__version__

'1.18.1'

In [300]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [303]:
x = np.linspace(10,15,10)
x

array([10.        , 10.55555556, 11.11111111, 11.66666667, 12.22222222,
       12.77777778, 13.33333333, 13.88888889, 14.44444444, 15.        ])

In [305]:
x = np.ones((2,3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [306]:
x = np.zeros((2,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [309]:
x = np.logspace(1,10)
print(x)

[1.00000000e+01 1.52641797e+01 2.32995181e+01 3.55648031e+01
 5.42867544e+01 8.28642773e+01 1.26485522e+02 1.93069773e+02
 2.94705170e+02 4.49843267e+02 6.86648845e+02 1.04811313e+03
 1.59985872e+03 2.44205309e+03 3.72759372e+03 5.68986603e+03
 8.68511374e+03 1.32571137e+04 2.02358965e+04 3.08884360e+04
 4.71486636e+04 7.19685673e+04 1.09854114e+05 1.67683294e+05
 2.55954792e+05 3.90693994e+05 5.96362332e+05 9.10298178e+05
 1.38949549e+06 2.12095089e+06 3.23745754e+06 4.94171336e+06
 7.54312006e+06 1.15139540e+07 1.75751062e+07 2.68269580e+07
 4.09491506e+07 6.25055193e+07 9.54095476e+07 1.45634848e+08
 2.22299648e+08 3.39322177e+08 5.17947468e+08 7.90604321e+08
 1.20679264e+09 1.84206997e+09 2.81176870e+09 4.29193426e+09
 6.55128557e+09 1.00000000e+10]


In [312]:
x = np.linspace(10,15,10,endpoint=False)
print(type(x))
print(x)
print(x[-3])

<class 'numpy.ndarray'>
[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5]
13.5


In [313]:
print(x[2:5])

[11.  11.5 12. ]


In [317]:
x = np.array(([1,2],[3,4]))
print(type(x))
print(x)
print(x[1][1])

<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
4


In [1]:
L = [1,4,5] #min = 0
min(L)    #min predefined function and it cannot be assigned as variable name
          #'int' object is not callable

1

In [4]:
import numpy as np
x = np.array([[[1,2],[2,3]],[[3,4],[6,7]],[[2,3],[5,6]]])
print(x)
print(type(x))

[[[1 2]
  [2 3]]

 [[3 4]
  [6 7]]

 [[2 3]
  [5 6]]]
<class 'numpy.ndarray'>


In [5]:
x1 = x.copy()
x1[2][1] = 300
print(x1)

[[[  1   2]
  [  2   3]]

 [[  3   4]
  [  6   7]]

 [[  2   3]
  [300 300]]]


In [7]:
x2 = x.view()
x2[2][1] = 300
print(x2)
print(x)

[[[  1   2]
  [  2   3]]

 [[  3   4]
  [  6   7]]

 [[  2   3]
  [300 300]]]
[[[  1   2]
  [  2   3]]

 [[  3   4]
  [  6   7]]

 [[  2   3]
  [300 300]]]


In [9]:
#base is not a function it is an attribute
print(x1.base)

None


In [12]:
print(x2.base)

[[[  1   2]
  [  2   3]]

 [[  3   4]
  [  6   7]]

 [[  2   3]
  [300 300]]]


In [13]:
x.dtype

dtype('int32')

In [14]:
x.size

12

In [15]:
x.shape

(3, 2, 2)

In [16]:
x.itemsize

4

In [17]:
print(x.dtype)
x1 = x.astype('float32')
print(x1.dtype)

int32
float32


In [19]:
x = np.array([1,2,3,4,5,6,7,8])
y = x.reshape(2,4)
print(y)

[[1 2 3 4]
 [5 6 7 8]]


In [20]:
x = np.array([1,2,3,4,5,6,7,8])
y = x.reshape(2,2,-1)
print(y)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
x = np.array([1,2,3,4],dtype='float64')
x.itemsize

8

In [22]:
x = np.array([1,2,3,4],dtype='float32')
x.itemsize

4

In [23]:
x = np.array([1,2,3,4],dtype='bool')
x.itemsize

1

In [24]:
x = np.array([1,2,3,4],dtype='int64')
x.itemsize

8

In [26]:
a = np.array([1,2,3,4,5])
b = np.array([10,9,8,7,6])
print(a+b)

[11 11 11 11 11]


In [27]:
print("mul",a*b)
print("div",b//a)
print("mod",b%a)
print("power",b**a)

mul [10 18 24 28 30]
div [10  4  2  1  1]
mod [0 1 2 3 1]
power [  10   81  512 2401 7776]


In [28]:
print(a>4)

[False False False False  True]


In [29]:
a[a>3]

array([4, 5])

In [30]:
a = np.ones((3,3))
b = np.full((3,3),5)
print(a+b)

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [31]:
a = np.ones((3,3))
b = np.full((3,3),5)
print(a*b)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [32]:
a.dot(b)

array([[15., 15., 15.],
       [15., 15., 15.],
       [15., 15., 15.]])

In [34]:
x = np.array([1,2,3,4,5,6])
print(x.sum())
print(x.mean())
print(x.cumsum())
print(x.std())
print(x.var())

21
3.5
[ 1  3  6 10 15 21]
1.707825127659933
2.9166666666666665


In [35]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [36]:
np.cbrt(x)

array([1.        , 1.25992105, 1.44224957, 1.58740105, 1.70997595,
       1.81712059])

In [37]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

In [38]:
np.abs(x)

array([1, 2, 3, 4, 5, 6])

In [39]:
np.product(x)

720

In [40]:
np.log2(x)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 ])

In [41]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125])

In [42]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ])

In [43]:
np.cos(x)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029])

In [45]:
y = np.array([[1,2,3,4],[4,5,6,7]])
print(y)

[[1 2 3 4]
 [4 5 6 7]]


In [46]:
for i in y:
    print(i)

[1 2 3 4]
[4 5 6 7]


In [49]:
for row in y:
    for i in row:
        print(i,end=" ")

1 2 3 4 4 5 6 7 

In [50]:
for i,e in enumerate(y):
    print(i,e)

0 [1 2 3 4]
1 [4 5 6 7]


In [52]:
a = np.array([1,2,3,4])
b = np.array([3,5,6,7])
a+b

array([ 4,  7,  9, 11])

In [53]:
c = np.concatenate((a,b))
print(c)

[1 2 3 4 3 5 6 7]


In [55]:
x = np.array([1,2,3,4,5,6,7,8])
np.where(x==5)

(array([4], dtype=int64),)

In [56]:
b = np.random.rand()
print(b)

0.8558330274279287


In [57]:
b = np.random.randint(2,3)
print(b)

2


In [68]:
b = np.random.rand(50)
print(b)

[7.97354333e-04 1.11149666e-01 5.01317656e-01 9.74141975e-01
 9.00392743e-01 9.83376783e-01 2.10137965e-01 3.21946903e-01
 4.63356089e-01 7.43255753e-01 8.12182430e-01 7.52629341e-01
 7.39113433e-01 9.90055136e-01 8.80746444e-01 8.95346408e-01
 5.52948459e-01 1.05769413e-03 4.08053161e-01 3.15890049e-03
 9.63054101e-01 2.84458645e-01 5.57552847e-01 4.76663601e-01
 8.09449053e-01 5.38328713e-01 2.84319362e-01 3.20663906e-01
 2.81585979e-02 2.22916888e-01 8.55935461e-01 9.41826834e-01
 3.24812809e-01 2.85145486e-01 4.42213122e-01 3.92402672e-02
 4.18013402e-01 4.10575749e-01 8.64981210e-01 1.79019149e-01
 9.86975986e-01 9.82704585e-01 6.79196557e-01 5.58996374e-01
 6.23278456e-01 6.08106642e-01 5.72878115e-01 3.52901819e-01
 9.32155146e-01 4.47494435e-01]


In [72]:
np.savetxt("random.txt",b)

In [74]:
p = np.loadtxt("random.txt")
print(p)

[7.97354333e-04 1.11149666e-01 5.01317656e-01 9.74141975e-01
 9.00392743e-01 9.83376783e-01 2.10137965e-01 3.21946903e-01
 4.63356089e-01 7.43255753e-01 8.12182430e-01 7.52629341e-01
 7.39113433e-01 9.90055136e-01 8.80746444e-01 8.95346408e-01
 5.52948459e-01 1.05769413e-03 4.08053161e-01 3.15890049e-03
 9.63054101e-01 2.84458645e-01 5.57552847e-01 4.76663601e-01
 8.09449053e-01 5.38328713e-01 2.84319362e-01 3.20663906e-01
 2.81585979e-02 2.22916888e-01 8.55935461e-01 9.41826834e-01
 3.24812809e-01 2.85145486e-01 4.42213122e-01 3.92402672e-02
 4.18013402e-01 4.10575749e-01 8.64981210e-01 1.79019149e-01
 9.86975986e-01 9.82704585e-01 6.79196557e-01 5.58996374e-01
 6.23278456e-01 6.08106642e-01 5.72878115e-01 3.52901819e-01
 9.32155146e-01 4.47494435e-01]


In [80]:
for i in range(10, 6, -1):
    for j in range(i):
        print('*',end=" ")
    print(' ')

* * * * * * * * * *  
* * * * * * * * *  
* * * * * * * *  
* * * * * * *  


In [90]:
n = int(input("enter number"))
for i in range(n):
    if i == n//2:
        for k in range(n//2,0,-1):
            for l in range(k):
                print('*',end=" ")
            print('')
        break
    else:
        for j in range(i):
            print('*',end=" ")
        print('')

enter number8

* 
* * 
* * * 
* * * * 
* * * 
* * 
* 


#### Generate the following pattern

In [14]:
'''
- *
- * *
- * * *
- * * * *
- * * * * *
'''
for i in range(6):
    for j in range(i):
        print('*',end=" ")
    print('')


* 
* * 
* * * 
* * * * 
* * * * * 


#### Euclidian distance between two lists of length n
- Ex: L1=[5,8,6,7]    L2=[4,9,3,1] Sqrt((5-4)**2+ (8-9)**2 + ..... )


In [85]:
import math 
L1=[5,8,6,7] 
L2=[4,9,3,1] 
result = 0
for i in range(len(L1)):
    for j in range(len(L2)):
        if i==j:
            result += (L1[i]-L2[i])**2
euc_dist = math.sqrt(result)

In [86]:
euc_dist

6.855654600401044

#### Display frequency of each element of a list and then delete duplicates

In [106]:
l = [1,2,3,5,2,1,2,3,4,5,3,2,1,6,7,8,2]
d = {}
for i in l:
    d[i] = l.count(i)

In [105]:
d

{1: 3, 2: 5, 3: 3, 5: 2, 4: 1, 6: 1, 7: 1, 8: 1}

In [107]:
l1 = list(set(l))
l1

[1, 2, 3, 4, 5, 6, 7, 8]

#### Find sum of integer or float values of a list

In [110]:
l = [9.0,2.0,3.6,5.2,4.6,2.1]
sum_values = 0
for i in l:
    sum_values += i 
sum_values

26.5